[package]
name = "fleximq-peer"
version.workspace = true
edition.workspace = true

[dependencies]
fleximq-protocol.workspace = true
fleximq-transport.workspace = true
async-trait.workspace = true
bytes.workspace = true
log.workspace = true
tokio-util.workspace = true
rmpv.workspace = true
rmp-serde.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
ulid.workspace = true
url.workspace = true
pin-project = "1"
crossbeam-queue = "0.3"
futures-util.workspace = true
tower.workspace = true
dashmap.workspace = true
triomphe.workspace = true
unsize.workspace = true

[lints]
workspace = true

[dev-dependencies]
env_logger = "0.11"
