[package]
name = "fleximq-transport"
edition.workspace = true
version.workspace = true

[dependencies]

# Async runtime
tokio.workspace = true
async-trait.workspace = true

# Error handling
thiserror.workspace = true

# Data structures
bytes.workspace = true
lru = "0.14"
dashmap.workspace = true

# URL parsing
url.workspace = true

# Socket utilities
socket2 = { version = "0.5", features = ["all"] }

# WebSocket
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
futures-util.workspace = true
http = "1.3"

# Deserialization

[dev-dependencies]
mockall = "0.13"
tempfile = "3.20"

[lints]
workspace = true
