[package]
name = "zeroio-protocol"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

# Async runtime
tokio = { version = "1.45", features = ["full"] }
futures = "0.3"

# External crates
serde.workspace = true
rmp-serde.workspace = true
bytes.workspace = true
thiserror.workspace = true
