[package]
name = "fleximq-protocol"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

# External crates
serde.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true
bytes.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
nom.workspace = true
futures-util.workspace = true
once_cell.workspace = true

# Zero-copy optimizations
memchr = "2.7"

[dev-dependencies]
serde_json = "1.0"
