[package]
name = "fleximq-protocol"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]

# External crates
serde.workspace = true
rmp-serde.workspace = true
bytes.workspace = true
thiserror.workspace = true
once_cell.workspace = true
lru.workspace = true

# Zero-copy optimizations
memchr = "2.7"
